config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'static_pages/home'

  get 'static_pages/video'
  get 'static_pages/detail'
  post 'static_pages/create'

   root 'static_pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:video_id, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'open-uri'
  require 'json'
  require 'uri'

  DEVELOPER_KEY ="AIzaSyDxSiM2u26mPlea4QK522XxnP2_d2CtFu0"
  
  def home
  end

  def video

    @video_data_param = params.require(:video_data).permit(:word)
    @word = @video_data_param["word"]

    
    url = "https://www.googleapis.com/youtube/v3/search?part=snippet&q="+ @word + "&key=" + DEVELOPER_KEY + "&maxResults=10"
    #日本語入力
    url = URI.escape(url)
    
    res = open(url)
    result = res.read
    video_response = JSON.parse(result)
    
    @video_result = ""
    
    video_response["items"].each do |row|
      if row["id"]["kind"].to_s.eql?("youtube#video") then
        @video_result += "<tr>"
        @video_result += "<td><a href='" + url_for(:controller => 'static_pages', :action => 'detail', :word => @word, :video => row["id"]["videoId"], :title => row["snippet"]["title"]) + "'><img src='" + row["snippet"]["thumbnails"]["medium"]["url"].to_s + "'/></td>"
        @video_result += "<td><h3>" + row["snippet"]["title"].to_s + "</h3><br/><font color='gray'>" + row["snippet"]["description"].to_s + "</font></td>"
        @video_result += "</tr>"
      end
    end
  end
  
  def detail
    @word = params["word"]
    @video_id = params["video"]
    @title = params["title"]
    @video_ch = params["video_ch"]
    @posts = Post.where(:video_id => @video_id)
    @post = Post.new
    session[:video_id] = @video_id
  end
  
  def create
    @post = Post.new(params.require(:post).permit(:video_id, :content))
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to :action => "detail",:video => session[:video_id], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YoutubeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar">
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://ruby-sample-miyazaki-yuuya.c9users.io/static_pages/home">YoutubeApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li><%= link_to "Home", :controller => "static_pages", :action => "home" %><span class="sr-only">(current)</span></li>
 
     </ul>
   </div>

</header>



<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video_id %><br>
    <%= f.text_field :video_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.video_id %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>
  <%= @post.video_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/detail.html.erb
<div class="sky-form" role="form">
    <%= form_tag(static_pages_video_path, :method => :get) do %>
        <%= text_field :video_data, :word, value: @word %>
        <%= submit_tag  '検索', class: 'btn btn-large btn-primary' %>
    <% end %>
</div>

<h1>detail</h1>

  <div class="flexbox">
   <section class="main">
    <iframe id="ytplayer" type="text/html" width="640" height="360"
      src="https://www.youtube.com/embed/<%= @video_id %>?autoplay=1"
      frameborder="0"/>
    </iframe>
   </section>
   <section class="side">

    <%= form_for(@post, :url => {:controller => :static_pages,:action => 'create'}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.hidden_field :video_id, :value => @video_id %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  
  <div class='comment'>
 <ul>
  <% @posts.each do |post| %>
  <li><%= post.content %></li>
  <% end %>
 </ul>
</div>


   </section>
  </div>

app/views/static_pages/home.html.erb
<h1>Home</h1>

<p>Find me in app/views/static_pages/home.html.erb</p>

<div class="sky-form" role="form">
    <%= form_tag(static_pages_video_path, :method => :get) do %>
        <%= text_field :video_data, :word %>
        <%= submit_tag  '検索', class: 'btn btn-large btn-primary' %>
    <% end %>
</div>

app/views/static_pages/video.html.erb
<div class="sky-form" role="form">
    <%= form_tag(static_pages_video_path, :method => :get) do %>
        <%= text_field :video_data, :word, value: @word %>
        <%= submit_tag  '検索', class: 'btn btn-large btn-primary' %>
    <% end %>
</div>

<h1>StaticPages#video</h1>
<p>Find me in app/views/static_pages/video.html.erb</p>
<p><%= @title %></p>
<p>検索表示：</p>
<table><tbody>
<%= @video_result.html_safe %>
</tbody></table>